### ISSUE TITLE
SvelteKit errors

### ISSUE THREAD

**Issue by BillBuilt** [rgossiaux/svelte-heroicons#1]
Just wanted to let ya know that I was getting the following when issuing `npm run dev` using SvelteKit when trying to import icons:
```
500
Directory import '/Users/[...]/frontend/node_modules/@rgossiaux/svelte-heroicons/outline/AcademicCap' is not supported resolving ES modules imported from /Users/[...]/frontend/node_modules/@rgossiaux/svelte-heroicons/outline/index.js
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/Users/[...]/frontend/node_modules/@rgossiaux/svelte-heroicons/outline/AcademicCap' is not supported resolving ES modules imported from /Users/[...]frontend/node_modules/@rgossiaux/svelte-heroicons/outline/index.js
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:390:17)
    at moduleResolve (node:internal/modules/esm/resolve:915:10)
    at defaultResolve (node:internal/modules/esm/resolve:1005:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
    at link (node:internal/modules/esm/module_job:78:36)
```

I was reading some of the other svelte heroicons packages and someone mentioned adding the following to `svelte.config.js` under `kit:` if they encountered any issues and it seems to have fixed the above for me. 

```
  ...
  kit: {
    vite: {
      ssr: {
        noExternal: ["@rgossiaux/svelte-heroicons"],
      },
    },
    adapter: adapter(),
    ...
  },
```

**Comment by zmre** [comment]
I'm getting that same error. I think the fix might be to change:

`export { AcademicCap as AcademicCapIcon } from "./AcademicCap";`

to

`export { AcademicCap as AcademicCapIcon } from "./AcademicCap/index.js";`

(and on with each of the exports).

But someone would have to try that to confirm. But @BillBuilt's fix did stop the errors for me, too. I think doing the above, if it works as I hope, would be a better fix for everyone though.

**Comment by rgossiaux** [comment]
Thanks for the report! I just implemented the suggestion from @zmre's comment and published it on npm as v0.1.1. Can you check and confirm if that fixes the problem for you?

**Comment by zmre** [comment]
Hmmm. If I remove @BillBuilt's workaround config and use 0.1.1, I get these errors:

```
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension
 ".svelte" for /[redacted]/node_modules/.pnpm/@rgossiaux+svelte-heroicons@0.1.1_svelte@3.46.4/node_modules/@rgossiaux/svelte-heroicons/outline/AcademicCap/AcademicCap.svelte
    at new NodeError (internal/errors.js:322:7)
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:71:15)
    at Loader.getFormat (internal/modules/esm/loader.js:105:42
)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:31)
    at async ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:78:21)
    at async Promise.all (index 0)
    at async link (internal/modules/esm/module_job.js:83:9)
Unknown file extension ".svelte" for /[redacted]/node_modules/.pnpm/@rgossiaux+svelte-heroicons@0.1.1_svelte@3.46.4/node_modules/@rgossiaux/svelte-heroicons/outline/AcademicCap/AcademicCap.svelte
```

This is in a svelte-kit project where my `.svelte` files are handled just fine. Don't have time to mess with it more tonight, but for me at least, it isn't yet fixed.

**Comment by rgossiaux** [comment]
@zmre Aha, this is a packaging problem. I think it may be fixed in 0.1.2--when you have a chance, give that a go and let me know if you still have this error.

**Comment by zmre** [comment]
👍  Works for me now without the config file hack. Thanks @rgossiaux!

**Comment by rgossiaux** [comment]
Great, thank you! I'll close this barring any other problems.
