### ISSUE TITLE
All icons load automatically

### ISSUE THREAD

**Issue by sureshjoshi** [rgossiaux/svelte-heroicons#2]
So, this may be a Svelte thing, a SvelteKit thing, or ... some other thing. But, I'm using this library in a project, and I've imported a couple of icons: `import { MenuIcon, UserIcon, XIcon } from "@rgossiaux/svelte-heroicons/solid";`

However, on running my application, I see that all heroicons (and headlessui components, incidentally) are loaded at once on page refresh in my dev server. 

![Screen Shot 2022-02-24 at 11 24 14](https://user-images.githubusercontent.com/3823045/155565192-59af4933-ac04-4d7c-8d24-6f2f168866c2.png)

I see in my network explorer that these files are imported:
`http://localhost:8080/node_modules/@rgossiaux/svelte-headlessui/index.js?t=1645717182624`
`http://localhost:8080/node_modules/@rgossiaux/svelte-heroicons/solid/index.js?t=1645717182624&v=9b4f8992`

and each of those then re-export all components in the projects.

Is that intended?

**Comment by rgossiaux** [comment]
Yeah, I believe this is related to https://github.com/sveltejs/kit/issues/2612 Personally I see this in dev mode but not in production.

Though even turning on the experimental setting mentioned in that issue, I see all the icons being prebundled together into one big file in dev mode. I'm not sure if there's an alternate way of managing the exports that would fix this--it needs some more investigation.

**Comment by sureshjoshi** [comment]
Ah, okay, thanks for pointing me at the SvelteKit issue - I didn't see that one. I'm also only seeing it in dev, and I only noticed it because of one weird use case which required full refreshes

**Comment by Obeyed** [comment]
Importing each icon directly doesn't load all icons:
```import UserIcon from "@rgossiaux/svelte-heroicons/solid/User"```

**Comment by sureshjoshi** [comment]
Closing, as this isn't a heroicons problem.
