### ISSUE TITLE
Heroicons 2.0v

### ISSUE THREAD

**Issue by candidosales** [rgossiaux/svelte-heroicons#3]
Do you have a plan to upgrade to Heroicons 2.0v?

https://twitter.com/steveschoger/status/1562117153591107586

**Comment by sureshjoshi** [comment]
For anyone who is interested, I have a partial fork updated to 2.0.15 (https://github.com/RobotPajamas/svelte-heroicons - https://www.npmjs.com/package/@robotpajamas/svelte-heroicons)

I haven't updated the docs yet (nor have I released the non-RC), as I'm waiting on one remaining `svelte-package` related problem. The generated types completely wipe out the `class` intellisense.
