### ISSUE TITLE
SSR Components

### ISSUE THREAD

**Issue by EternalWill43** [rgossiaux/svelte-heroicons#6]
I'm using the [svg-to-svelte](https://github.com/metonym/svg-to-svelte) library to convert some of the newer icons that aren't in the svelte-heroicons library. In this example in the `node_modules/@rgossiaux/svelte-heroicons/solid` folder, I created a `MagnifyingGlass` folder, I used that svg-to-svelte library to generate the MagnifyingGlass.svelte and index.js files, then I also created the index.d.ts file & MagnifyingGlass.svelte.d.ts files and copied the format from the other examples in folders.

I then added the exports for it in `/solid/index.d.ts` and `/solid/index.js` and also added the export to the package.json in the root `@rgossiaux` folder.

When I try to import the icon into a svelte component in my sveltekit project, I get this error, but only for my components and not for any of the ones that were already in the library.

`Error: <MagnifyingGlassIcon> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules. Otherwise you may need to fix a <MagnifyingGlassIcon>`

**Comment by sureshjoshi** [comment]
@EternalWill43  Can you try this out and see if it's the same problem? 

https://www.npmjs.com/package/@robotpajamas/svelte-heroicons

`"@robotpajamas/svelte-heroicons": "2.0.15-rc.3"`

I'm using it for a sveltekit project, but I'm not seeing this issue. I may also be rendering client-side, now that I think about it.
